export enum FileType {
    PROFILE_PICTURE = 'PROFILE_PICTURE',
    USER_NID = 'USER_NID',
    USER_BIRTH_CERTIFICATE = 'USER_BIRTH_CERTIFICATE',
    USER_TIN_CERTIFICATE = 'USER_TIN_CERTIFICATE',
    USER_PASSPORT = 'USER_PASSPORT',

    NOMINEE_PICTURE = 'NOMINEE_PICTURE',
    NOMINEE_NID = 'NOMINEE_NID',
    NOMINEE_BIRTH_CERTIFICATE = 'NOMINEE_BIRTH_CERTIFICATE',
    NOMINEE_TIN_CERTIFICATE = 'NOMINEE_TIN_CERTIFICATE',
    NOMINEE_PASSPORT = 'NOMINEE_PASSPORT',

    EDUCATION_CERTIFICATE = 'EDUCATION_CERTIFICATE',
    EDUCATION_MARKSHEET = 'EDUCATION_MARKSHEET',
    TRAINING_CERTIFICATE = 'TRAINING_CERTIFICATE',
    WORK_EXPERIENCE_CERTIFICATE = 'WORK_EXPERIENCE_CERTIFICATE',
    PROFESSIONAL_QUALIFICATION_CERTIFICATE = 'PROFESSIONAL_QUALIFICATION_CERTIFICATE',
    OFFICE_LOGO = 'OFFICE_LOGO',
    TICKET_ATTACHMENT = 'TICKET_ATTACHMENT'
}
